frameworkVersion: "3"
service: database-backups

plugins:
  - serverless-vpc-discovery
  - serverless-plugin-utils

provider:
  name: aws
  region: eu-west-2
  stage: ${env:STAGE}
  timeout: 900

  deploymentBucket:
    name: "trade-tariff-lambda-deployment-${aws:accountId}"

  ecr:
    images:
      database-backups:
        uri: "${env:ECR_URL}:${env:DOCKER_TAG}"

  environment:
    ENVIRONMENT: ${sls:stage}
    S3_BUCKET: "trade-tariff-database-backups-${aws:accountId}"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:DeleteObject
        - s3:GetObject
        - s3:ListBucket
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::trade-tariff-database-backups-${aws:accountId}"
        - "arn:aws:s3:::trade-tariff-database-backups-${aws:accountId}/*"

    - Effect: "Allow"
      Action:
        - secretsmanager:GetResourcePolicy
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
        - secretsmanager:ListSecretVersionIds
      Resource:
        - "arn:aws:secretsmanager:eu-west-2:${aws:accountId}:secret:aurora-postgres-rw-connection-string-*"
        - "arn:aws:secretsmanager:eu-west-2:${aws:accountId}:secret:*-postgres-database-url-*"

    - Effect: "Allow"
      Action:
        - kms:Encrypt
        - kms:Decrypt
        - kms:ReEncryptFrom
        - kms:ReEncryptTo
        - kms:GenerateDataKey
        - kms:GenerateDataKeyPair
        - kms:GenerateDataKeyPairWithoutPlainText
        - kms:GenerateDataKeyWithoutPlaintext
      Resource:
        - arn:aws:kms:eu-west-2:${aws:accountId}:key/*

    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"

functions:
  backup:
    image: database-backups
    environment:
      DATABASE_SECRET: ${env:DATABASE_SECRET}
    vpcDiscovery:
      vpcName: "trade-tariff-${sls:stage}-vpc"
      subnets:
        - tagKey: "Name"
          tagValues:
            - "*private*"
      securityGroups:
        - names:
            - "trade-tariff-be-rd-${sls:stage}"
            - "trade-tariff-alb-security-group-${sls:stage}"
    events:
      - schedule: cron(0 9 * * ? *) # Run every day at 0900 UTC (BWT)
